### PR TITLE
Re 9 deprecate package

### LINKED ISSUE #9: Deprecate this package for backwards compatibility.
As this package got integrated into Zope with https://github.com/zopefoundation/Zope/commit/cc059e24c1280bc9eaf077a9adbee1bb4267a7c3, it is reasonable to have a release `99.0` which only contains the `configure.zcml` and `meta.zcml`. This allows to keep the code base which includes `five.pt` but ensures that it has no effect with Zope 4.

### PR DESCRIPTION
**Pull request by sallner**
Fixes #9.

### CODE REVIEW

**Comment by tseaver** [comment]
As an example of what I mean, see https://github.com/zopefoundation/initgroups/pull/3 ,

**Comment by sallner** [comment]
I will modify the PR to issue deprecation warnings.

**Comment by jensens** [comment]
I do not know if it helps, but for Plone we created a deprecation guide at https://docs.plone.org/develop/styleguide/deprecation.html - just fyi.

**Comment by tseaver** [comment]
@sallner I'd like to make an actual `2.3` release (not the `99.0` quasi-version used in this PR).

**Comment by jensens** [comment]
@tseaver, isnt it more than a feature but a breaking change? So according to semantic versioning it should be a major increase. I agree with you, 99 is a very bold and confusing. I would expect the next major: 3.0

**Comment by tseaver** [comment]
@jensens To my view, it is *not* a breaking change:  software which worked on version `2.2.x` will continue to work on the new version (whatever we label it).  The only difference is that we are declaring that there will be no more development, and pointing people to the locations they should be using.

**Comment by jensens** [comment]
@tseaver Ok, you convinced me. Deprecation messages do not break anything. They are just annoying :)

**Comment by icemac** [comment]
@tseaver I think this change should be a version 3.0 as software using Zope 2.13 will **not** run with this new version only software running on Zope 4 can use this version and is forced to use it as 2.2 is not compatible with Zope 4 because of the code moved there from this package.

Actually I came up with the suggestion of 99.0 as version number. This will be the last release of this package as it is now empty. Such a high version number could signal that there is something "wrong" with this package what users of the package should investigate further.

**Pull request merged**
